//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:yarn_spinner.compiler.framework/src/yarn_spinner_parser.dart';

// Generated from /Users/desplesda/Work/yarnspinner/YarnSpinner.Compiler/YarnSpinnerParser.g4 by ANTLR 4.8

// Unreachable code detected
// The variable '...' is assigned but its value is never used
// Missing XML comment for publicly visible type or member '...'
// Ambiguous reference in cref attribute


abstract class IYarnSpinnerParserListener implements IParseTreeListener {
  void enterDialogue(DialogueContext context);
  void exitDialogue(DialogueContext context);
  void enterFile_hashtag(File_hashtagContext context);
  void exitFile_hashtag(File_hashtagContext context);
  void enterNode(NodeContext context);
  void exitNode(NodeContext context);
  void enterHeader(HeaderContext context);
  void exitHeader(HeaderContext context);
  void enterBody(BodyContext context);
  void exitBody(BodyContext context);
  void enterStatement(StatementContext context);
  void exitStatement(StatementContext context);
  void enterLine_statement(Line_statementContext context);
  void exitLine_statement(Line_statementContext context);
  void enterLine_formatted_text(Line_formatted_textContext context);
  void exitLine_formatted_text(Line_formatted_textContext context);
  void enterHashtag(HashtagContext context);
  void exitHashtag(HashtagContext context);
  void enterLine_condition(Line_conditionContext context);
  void exitLine_condition(Line_conditionContext context);
  void enterExpParens(ExpParensContext context);
  void exitExpParens(ExpParensContext context);
  void enterExpMultDivMod(ExpMultDivModContext context);
  void exitExpMultDivMod(ExpMultDivModContext context);
  void enterExpComparison(ExpComparisonContext context);
  void exitExpComparison(ExpComparisonContext context);
  void enterExpNegative(ExpNegativeContext context);
  void exitExpNegative(ExpNegativeContext context);
  void enterExpAndOrXor(ExpAndOrXorContext context);
  void exitExpAndOrXor(ExpAndOrXorContext context);
  void enterExpAddSub(ExpAddSubContext context);
  void exitExpAddSub(ExpAddSubContext context);
  void enterExpNot(ExpNotContext context);
  void exitExpNot(ExpNotContext context);
  void enterExpValue(ExpValueContext context);
  void exitExpValue(ExpValueContext context);
  void enterExpEquality(ExpEqualityContext context);
  void exitExpEquality(ExpEqualityContext context);
  void enterValueNumber(ValueNumberContext context);
  void exitValueNumber(ValueNumberContext context);
  void enterValueTrue(ValueTrueContext context);
  void exitValueTrue(ValueTrueContext context);
  void enterValueFalse(ValueFalseContext context);
  void exitValueFalse(ValueFalseContext context);
  void enterValueVar(ValueVarContext context);
  void exitValueVar(ValueVarContext context);
  void enterValueString(ValueStringContext context);
  void exitValueString(ValueStringContext context);
  void enterValueNull(ValueNullContext context);
  void exitValueNull(ValueNullContext context);
  void enterValueFunc(ValueFuncContext context);
  void exitValueFunc(ValueFuncContext context);
  void enterVariable(VariableContext context);
  void exitVariable(VariableContext context);
  void enterFunction_call(Function_callContext context);
  void exitFunction_call(Function_callContext context);
  void enterIf_statement(If_statementContext context);
  void exitIf_statement(If_statementContext context);
  void enterIf_clause(If_clauseContext context);
  void exitIf_clause(If_clauseContext context);
  void enterElse_if_clause(Else_if_clauseContext context);
  void exitElse_if_clause(Else_if_clauseContext context);
  void enterElse_clause(Else_clauseContext context);
  void exitElse_clause(Else_clauseContext context);
  void enterSet_statement(Set_statementContext context);
  void exitSet_statement(Set_statementContext context);
  void enterCall_statement(Call_statementContext context);
  void exitCall_statement(Call_statementContext context);
  void enterCommand_statement(Command_statementContext context);
  void exitCommand_statement(Command_statementContext context);
  void enterCommand_formatted_text(Command_formatted_textContext context);
  void exitCommand_formatted_text(Command_formatted_textContext context);
  void enterShortcut_option_statement(Shortcut_option_statementContext context);
  void exitShortcut_option_statement(Shortcut_option_statementContext context);
  void enterShortcut_option(Shortcut_optionContext context);
  void exitShortcut_option(Shortcut_optionContext context);
  void enterDeclare_statement(Declare_statementContext context);
  void exitDeclare_statement(Declare_statementContext context);
  void enterJump_statement(Jump_statementContext context);
  void exitJump_statement(Jump_statementContext context);
}
// namespace Yarn.Compiler
