//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:yarn_spinner.compiler.framework/src/yarn_spinner_parser.dart';

// Generated from /Users/desplesda/Work/yarnspinner/YarnSpinner.Compiler/YarnSpinnerParser.g4 by ANTLR 4.8

// Unreachable code detected
// The variable '...' is assigned but its value is never used
// Missing XML comment for publicly visible type or member '...'
// Ambiguous reference in cref attribute


abstract class IYarnSpinnerParserVisitor<Result> implements IParseTreeVisitor<Result> {
  Result visitDialogue(DialogueContext context);
  Result visitFile_hashtag(File_hashtagContext context);
  Result visitNode(NodeContext context);
  Result visitHeader(HeaderContext context);
  Result visitBody(BodyContext context);
  Result visitStatement(StatementContext context);
  Result visitLine_statement(Line_statementContext context);
  Result visitLine_formatted_text(Line_formatted_textContext context);
  Result visitHashtag(HashtagContext context);
  Result visitLine_condition(Line_conditionContext context);
  Result visitExpParens(ExpParensContext context);
  Result visitExpMultDivMod(ExpMultDivModContext context);
  Result visitExpComparison(ExpComparisonContext context);
  Result visitExpNegative(ExpNegativeContext context);
  Result visitExpAndOrXor(ExpAndOrXorContext context);
  Result visitExpAddSub(ExpAddSubContext context);
  Result visitExpNot(ExpNotContext context);
  Result visitExpValue(ExpValueContext context);
  Result visitExpEquality(ExpEqualityContext context);
  Result visitValueNumber(ValueNumberContext context);
  Result visitValueTrue(ValueTrueContext context);
  Result visitValueFalse(ValueFalseContext context);
  Result visitValueVar(ValueVarContext context);
  Result visitValueString(ValueStringContext context);
  Result visitValueNull(ValueNullContext context);
  Result visitValueFunc(ValueFuncContext context);
  Result visitVariable(VariableContext context);
  Result visitFunction_call(Function_callContext context);
  Result visitIf_statement(If_statementContext context);
  Result visitIf_clause(If_clauseContext context);
  Result visitElse_if_clause(Else_if_clauseContext context);
  Result visitElse_clause(Else_clauseContext context);
  Result visitSet_statement(Set_statementContext context);
  Result visitCall_statement(Call_statementContext context);
  Result visitCommand_statement(Command_statementContext context);
  Result visitCommand_formatted_text(Command_formatted_textContext context);
  Result visitShortcut_option_statement(Shortcut_option_statementContext context);
  Result visitShortcut_option(Shortcut_optionContext context);
  Result visitDeclare_statement(Declare_statementContext context);
  Result visitJump_statement(Jump_statementContext context);
}
// namespace Yarn.Compiler
