name: Build Yarn Spinner

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main, 'feature/**' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Fetch all commits
      run: git fetch --unshallow

    - uses: gittools/actions/gitversion/setup@v0.9.10
      name: Install GitVersion
      with:
          versionSpec: '5.x'

    - uses: gittools/actions/gitversion/execute@v0.9.10
      name: Execute GitVersion
      id: gitversion # step id used as reference for output values
      with:
        updateAssemblyInfo: true
      
    - name: Print version information
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal